### ISSUE TITLE
Lab fails to setup [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by DustyArmstrong** [w4sp-book/w4sp-lab#40]
Lab fails to setup. It gets most of the way before it encounters a (presumably) fatal error and stops. 

`Exception happened during processing of request from ('127.0.0.1', 52164)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
`

Assuming with the "broken pipe" there's some issue with the connection being closed.

**Comment by DustyArmstrong** [comment]
I ran "setup" again after encountering this and that seemed to generate the nodes. I ran a test capture and it seems the lab is generating traffic. 

Not sure, I saved the machine state though in the hopes that if anything goes wrong I can revert.

**Comment by julio1925** [comment]
Refer to the installation Guide:

!!NOTE!! - There is currently a bug in lab startup!

If you run into an error where the lab setup is stuck at the "Setting Up Lab Environment...." screen and there is an error in the terminal about "Broken Pipe" - Simply refresh the browser and the lab will be fully functional, this is strictly a UI bug on initial setup.
