### ISSUE TITLE
Service network manager start error

### ISSUE THREAD

**Issue by danylux79** [w4sp-book/w4sp-lab#70]
hello 
i have modified all the file suggested, but at the end i receive this error:

['docker', 'build', '-t', 'w4sp/labs:elk', 'elk']
['docker', 'build', '-t', 'w4sp/labs:switch', 'switch']
['docker', 'build', '-t', 'w4sp/labs:ftp_tel', 'ftp_tel']
['docker', 'ps', '-aq', '--filter', 'label=w4sp=true']
['ifconfig', '-a']
['ip', 'link', 'delete', b'eth0:']
RTNETLINK answers: Operation not supported
['ip', 'link', 'delete', b'lo:']
RTNETLINK answers: Operation not supported
['ip', 'netns']
['pkill', 'dhclient']
['ifconfig', '-a']
['service', 'network-manager', 'start']
Failed to start network-manager.service: Unit network-manager.service not found.
Traceback (most recent call last):
  File "w4sp_webapp.py", line 521, in <module>
    w4sp.docker_clean()
  File "/home/w4sp-lab/Downloads/w4sp-lab-master/w4sp_app/utils.py", line 146, in docker_clean
    r('service network-manager start')
  File "/home/w4sp-lab/Downloads/w4sp-lab-master/w4sp_app/utils.py", line 83, in r
    return subprocess.check_output(cmd)
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['service', 'network-manager', 'start']' returned non-zero exit status 5.
w4sp-lab@kali:~/Downloads/w4sp-lab-master$ 

can you help me?
Thanks

**Comment by RikyTes** [comment]
Hi,

I had the same problem with kali 2020 and i solved it in this way:

In "/home/w4sp-lab/Downloads/w4sp-lab-master/w4sp_app/utils.py" 
change line 146:  r('service network-manager start') with r('service **NetworkManager** start')

It should work

**Comment by RikyTes** [comment]
I forgot one more thing:

In "/home/w4sp-lab/Downloads/w4sp-lab-master/w4asp.py"
change line 109: r('service network-manager stop') with r('service **NetworkManager** stop')

**Comment by danylux79** [comment]
Hello , many thanks for your answer.
i receive the same error 
i think that on my kali there is no service with name NetworkManager , it's possible? how can install it?

RTNETLINK answers: Operation not supported
['ip', 'link', 'delete', b'lo:']
RTNETLINK answers: Operation not supported
['ip', 'netns']
['pkill', 'dhclient']
['ifconfig', '-a']
['service', 'networkmanager', 'start']
Failed to start networkmanager.service: Unit networkmanager.service not found.
Traceback (most recent call last):
  File "w4sp_webapp.py", line 521, in <module>
    w4sp.docker_clean()
  File "/home/w4sp-lab/Downloads/w4sp-lab-master/w4sp_app/utils.py", line 146, in docker_clean
    r('service networkmanager start')
  File "/home/w4sp-lab/Downloads/w4sp-lab-master/w4sp_app/utils.py", line 83, in r
    return subprocess.check_output(cmd)
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['service', 'networkmanager', 'start']' returned non-zero exit status 5.

**Comment by danylux79** [comment]
OK , 
sorry but i forgot that i need to use case sensitive letter.
now seems to be work.
i can close the issue

**Comment by danylux79** [comment]
issue solved 
many thanks
