### ISSUE TITLE
Code Error Solved

### ISSUE THREAD

**Issue by ghost** [w4sp-book/w4sp-lab#87]
https://github.com/slowdodo/w4sp-lab

[kali_linux offical docker install doc](https://www.kali.org/docs/containers/installing-docker-on-kali/)

``` bash
useradd -m w4sp-lab -s /bin/bash -G sudo -U
```
``` bash
passwd w4sp-lab
```
`user change kali -> w4sp-lap `
(If you log in from the terminal with su w4sp , even sudo will not run. You need to log out and connect to w4sp.)
``` bash
git clone https://github.com/slowdodo/w4sp-lab.git
```
``` bash
sudo python ./w4sp-lab/w4sp_webapp.py
```

**Comment by andreacastelnuovo** [comment]
Hi, I have this problem:

Traceback (most recent call last):
File "/home/w4sp-lab/Downloads/w4sp-lab-master/w4sp_webapp.py", line 8, in
import w4sp
File "/home/w4sp-lab/Downloads/w4sp-lab-master/w4sp.py", line 23
print r('ls -sail /root')
^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

Do you know what I have to do? Or if you have the right code can share it? Thank you!

**Comment by ghost** [comment]
If the basic code problems in w4sp-book/w4sp-lab can be solved by changing the print(r"~~") format. However, there are also many other issues, it is advisable to download the code using 
``` bash
git clone https://github.com/slowdodo/w4sp-lab.git
``` 
If you only check the username, login status, root status, and Docker installation, the installation will proceed without any problems.

**Comment by andreacastelnuovo** [comment]
Ok thank you! I'm trying right now. I hope this solve the problems.

**Comment by andreacastelnuovo** [comment]
It stopped here:

['which', 'dumpcap']
['getcap', b'/usr/bin/dumpcap']
[*] Error, capabilities not set correctly on dumpcap, setting capabilities
['setcap', '-r', b'/usr/bin/dumpcap']
[*] Not enough w4sp/labs images found, building now
/home/w4sp-lab/w4sp-lab/images
['docker', 'build', '-t', 'w4sp/labs:base', 'base']
['docker', 'build', '-t', 'w4sp/labs:ftp_tel', 'ftp_tel']
['docker', 'build', '-t', 'w4sp/labs:samba', 'samba']
['docker', 'build', '-t', 'w4sp/labs:elk', 'elk']

Do you know an idea of where is the problem? I'm goin out crazy!!!!!!

**Comment by ghost** [comment]
Just install it as is. It looks like nothing is happening because you are downloading the image. It's downloading a Docker image using Python.
I tried running Kali Linux as an OVA on a laptop and it worked fine.
I will try it again on desktop later and check for errors.
Even if an error occurs, it should still work normally. Just wait for about 10 minutes.

**Comment by ghost** [comment]
![화면 캡처 2023-01-30 090459](https://user-images.githubusercontent.com/96872399/215363827-9bd4a548-f4a2-4c32-a159-eb0525573106.png)


Even on the desktop, it runs smoothly.
It's the latest version installed as a live VM through OVA or VMK, including Docker installation, user, and Python version.
If the installation is not working, try installing the latest Kali Linux through VMware or Virtualbox instead of the original Kali Linux.

It means to install a pre-built version of Kali Linux, not to reinstall it.
![화면 캡처 2023-01-30 091303](https://user-images.githubusercontent.com/96872399/215364244-22c9a760-8fa1-417c-a069-dceccbfd06bd.png)

**Comment by andreacastelnuovo** [comment]
Ok thank you so much! I try after.

**Comment by andreacastelnuovo** [comment]
It woooorks! Finally! I think the problem was just my internet connection, it's so slowly in kali. Thank you again!
